version: '3.1'
services:
  chrome:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5900:5900
    volumes:
      - ./app:/app
    shm_size: '2g'
    env_file:
      - app/.env
    environment:
      - DOCKER_RUN=1